arxiv:
  - https://arxiv.org/list/cs.AI/recent
  - https://arxiv.org/list/cs.CY/recent
  - https://arxiv.org/list/cs.CE/recent
  - https://arxiv.org/list/cs.HC/recent
  - https://arxiv.org/list/cs.IR/recent
  - https://arxiv.org/list/cs.LG/recent
  - https://arxiv.org/list/cs.MA/recent