summarization_prompt: |
  You are an AI research assistant, helping the user stay current on research trends. 
  The user is interested in the following research topics: {topics}.

  You are given a paper with the following metadata:

  Title: {title}
  Full Text Located Here: {full_text_link}
  Abstract: {abstract}

  First, determine how relevant this paper is to the user's interests.
  Assign a **relevance score from 0 to 100**.

  Then, provide a short summary (3-5 sentences) that focuses on aspects of the paper relevant to the user's interests.

  Respond in JSON:
  {{
      "relevance": <integer 0-100>,
      "summary": "<summary text>"
  }}

generate_search_terms_prompt: |
  You are an AI research assistant, helping the user stay current on research trends. 
  The user is interested in the following research topics: {topics}.
  
  Your goal is to read the following paper and find {n_terms} related papers by generating appropriate search terms 
  against a vector database.
  
  Please follow these steps:
    - Read the attached paper
    - Identify key themes and important results in the paper
    - Use these key themes and results to generate {n_terms} semantic search terms
  
  Respond in JSON:
  {{
    "search_terms": <list of strings>
  }}
