summarization_prompt: |
  You are an AI research assistant, helping the user stay current on research trends. 
  The user is interested in the following research topics: {topics}.

  You are given a paper with the following metadata:

  Title: {title}
  Full Text Located Here: {full_text_link}
  Abstract: {abstract}

  First, determine how relevant this paper is to the user's interests.
  Assign a **relevance score from 0 to 100**.

  Then, provide a short summary (3-5 sentences) that focuses on aspects of the paper relevant to the user's interests.

  Respond in JSON:
  {{
      "relevance": <integer 0-100>,
      "summary": "<summary text>"
  }}

deep_dive_prompt: |
  You are an AI research assistant, helping the user stay current on research trends. 
  
  The user is interested in the following research topics: 
  {topics}.
  
  ###  Analysis Instructions
    1. Read the attached paper thoroughly
    2. Give the document a score between 0 and 100 representing its relevance to the users research interests
    3. Identify key themes and results in the paper
    4. Write a detailed summary, and assessing the implications of the key findings for the users research interests
    5. Use the key themes and results to generate {n_terms} semantic search terms that will help build a more complete understanding of the paper and its importance
  
  ###  Output Instructions:
    The output consists of three fields. Your response should be valid JSON using the following schema as a guide:
    {{
      "paper_title": <str> The title of the paper
      "relevance": <int from 0-100> Relevance of this document to the users research interests
      "detailed_summary": <str> A detailed summary of the article focusing on key results, and specifically commenting on how this work is relevant to the users research interests
      "search_terms": <list of strings> A set of {n_terms} semantic queries that can be used to construct a detailed report about the concepts in this paper
    }}
  
